FROM node:8

USER root
WORKDIR /app

RUN npm install -g yarn
RUN yarn global add elm elm-test

COPY elm-package.json elm-package.json
RUN cat /app/elm-package.json
RUN elm-package install --yes

# static assets
COPY assets/ assets/

COPY src/ src/
RUN elm-make  src/Main.elm --output assets/elm.js

COPY index.html ./
RUN tar zcf build.tar.gz index.html assets/

