module Reactor exposing(update, view , init, subscriptions)

import Html exposing (div)

--
-- Init establishes the basic data structure.
--
init =
    ({} , Cmd.none)


-- Update is a triggered by a Msg which represents
-- a particular side-effect generated by an actor
--
update model msg =
    (model, Cmd.none)

--
-- view is invoked by updates to the model
--
view model =
    div [] []


subscriptions model =
    Sub.none

